name: story_sharing_app
description: A story sharing app with a social media interface.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  # Temporarily removing Firebase dependencies
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0
  # cloud_firestore: ^4.9.1
  # firebase_storage: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

