// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdjhtHgXdjzzYvNy-w1hQSwF97PlEH3o',
    appId: '1:355104130922:web:3cab8731c2875eef2b4713',
    messagingSenderId: '355104130922',
    projectId: 'empowerher-tales',
    authDomain: 'empowerher-tales.firebaseapp.com',
    storageBucket: 'empowerher-tales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFVpsKSMMavdVddUWdRkpKoKDjgDEu7Q',
    appId: '1:355104130922:android:2108585a3330ff5a2b4713',
    messagingSenderId: '355104130922',
    projectId: 'empowerher-tales',
    storageBucket: 'empowerher-tales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTfnK3ObnAFgT8i347r4fS2d2p7Muw1I',
    appId: '1:355104130922:ios:104da0846fbb8f0f2b4713',
    messagingSenderId: '355104130922',
    projectId: 'empowerher-tales',
    storageBucket: 'empowerher-tales.firebasestorage.app',
    iosBundleId: 'com.example.empowerherTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTfnK3ObnAFgT8i347r4fS2d2p7Muw1I',
    appId: '1:355104130922:ios:104da0846fbb8f0f2b4713',
    messagingSenderId: '355104130922',
    projectId: 'empowerher-tales',
    storageBucket: 'empowerher-tales.firebasestorage.app',
    iosBundleId: 'com.example.empowerherTales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWdjhtHgXdjzzYvNy-w1hQSwF97PlEH3o',
    appId: '1:355104130922:web:e5778de6f4f76c9b2b4713',
    messagingSenderId: '355104130922',
    projectId: 'empowerher-tales',
    authDomain: 'empowerher-tales.firebaseapp.com',
    storageBucket: 'empowerher-tales.firebasestorage.app',
  );
}
