// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQtFJ0RRZbxP0GywIyD2XG4QbQOr3_AYM',
    appId: '1:995635361097:web:0d183bc2e64fcb0c2ad698',
    messagingSenderId: '995635361097',
    projectId: 'empower-hertales',
    authDomain: 'empower-hertales.firebaseapp.com',
    storageBucket: 'empower-hertales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSwUvQ5dvFF2soZf44RphQR9gkAPN4zY',
    appId: '1:995635361097:android:0283a1039e1459c72ad698',
    messagingSenderId: '995635361097',
    projectId: 'empower-hertales',
    storageBucket: 'empower-hertales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUW70RTViSJPFh9HZreNqhF9kH4knCnSM',
    appId: '1:995635361097:ios:a3ef0c5f878d9bd82ad698',
    messagingSenderId: '995635361097',
    projectId: 'empower-hertales',
    storageBucket: 'empower-hertales.firebasestorage.app',
    iosBundleId: 'com.example.empowerherTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUW70RTViSJPFh9HZreNqhF9kH4knCnSM',
    appId: '1:995635361097:ios:a3ef0c5f878d9bd82ad698',
    messagingSenderId: '995635361097',
    projectId: 'empower-hertales',
    storageBucket: 'empower-hertales.firebasestorage.app',
    iosBundleId: 'com.example.empowerherTales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQtFJ0RRZbxP0GywIyD2XG4QbQOr3_AYM',
    appId: '1:995635361097:web:331a040b658bb6282ad698',
    messagingSenderId: '995635361097',
    projectId: 'empower-hertales',
    authDomain: 'empower-hertales.firebaseapp.com',
    storageBucket: 'empower-hertales.firebasestorage.app',
  );
}
